[IMP] hr_timesheet_usability: En lineas de analitica inicializar los …
avanzosc/hr-addons pull request #122
Opened 2022-01-24 14:36 UTC by alfredoavanzosc

…campos hora inicio y fin, y también empleado.

2022-01-24 14:36 UTC, alfredoavanzosc commented
@avanzosc/developers .... review please

2022-01-24 15:37 UTC, Daniel-CA approved these changes

2022-01-24 16:56 UTC, anajuaristi commented on hr_timesheet_usability/models/account_analytic_line.py
> +    time_start = fields.Float(default=default_times)
time_start y time_stop ya los crea hr_timesheet_activity_begin_end entonces, deberían estar aquí de nuevo? Es porque se les asigna aquí un default que no tienen en el otro lado?

2022-01-25 07:13 UTC, alfredoavanzosc commented on hr_timesheet_usability/models/account_analytic_line.py
> +    time_start = fields.Float(default=default_times)
Muy buenos días @anajuaristi , efectivamente, en el módulo origen los crea, pero no les da ningún valor por defecto, esto hacé que cuando se muestra el formulario o el tree con estos campos, aparezcan vacios. 
Con la modificación que yo he hecho al módulo "hr_timesheet_usability" les defino un default para que les de un valor por defecto.
Un saludo.

2022-02-09 16:55 UTC, oihane requested changes

2022-02-09 16:55 UTC, oihane commented on hr_timesheet_usability/models/account_analytic_line.py
> +    employee_id = fields.Many2one(default=default_employee_id)
En analitica NO SIEMPRE hay que informar el empleado.

2025-03-12 14:19 UTC, closed without merging