[ADD] <res_partner_working_calendar>: This module allows you to defin…
avanzosc/hr-addons pull request #40
Opened 2018-07-27 09:44 UTC by eideravanzosc

…e the working calendar for partners

@oihane , @Daniel-CA , @mikelarre , @alfredoavanzosc 

review, please

2018-07-27 09:57 UTC, oihane requested changes

2018-07-27 09:57 UTC, oihane commented on res_partner_working_calendar/__init__.py
> +# (c) 2018 Eider Oyarbide - AvanzOSC
no se pone `(c)` si no `copyright`

2018-07-27 09:57 UTC, oihane commented on res_partner_working_calendar/__openerp__.py
> +        "Alfredo de la Fuente <alfredodelafuente@avanzosc.es",
Si lo has hecho tu, porque pones a Alfredo

2018-07-27 09:57 UTC, oihane commented on res_partner_working_calendar/__openerp__.py
> +        "calendar_holiday",
@anajuaristi es contra 'calendar_holiday'?

2018-07-27 09:57 UTC, oihane commented on res_partner_working_calendar/models/res_partner.py
> +                                           string="Working calendar")
Falta un salto de línea

2018-07-27 09:57 UTC, oihane commented on res_partner_working_calendar/models/res_partner.py
> +from dateutil.relativedelta import relativedelta
No debes importar aquello que no se usa

2018-07-27 11:51 UTC, oihane commented
La solicitud era:

> Añadir en el partner un campo many2one a "horario" (el objeto que se puede meter lunes de tal hora a tal hora, martes de tal hora a tal hora... No me acuerdo del nombre del objeto)
> partner_opening_hours

No tiene nada que ver con HR, así que hay que mover este modulo, renombrado a odoo-addons y sus dependencias deben ser **base** y **resource**

@anajuaristi corrigeme si me equivoco

2018-07-30 14:33 UTC, anajuaristi commented on res_partner_working_calendar/__openerp__.py
> +        "hr_contract",
Exacto. No tiene dependencia con HR. Es un campo informativo en la ficha de partner lo que se está añadiendo y por tanto no requiere que se instale hr_contract.
Teneis que ver qué módulo instala el objeto resource y meterle dependencia con ese.

2018-07-30 14:33 UTC, anajuaristi commented on res_partner_working_calendar/models/res_partner.py
> +    working_calendar_ids = fields.Many2one(comodel_name="resource.calendar",
es un many2one, no un one2many por lo que entiendo que la variable tiene que ser en singular y no en plural.

2018-08-01 10:08 UTC, closed without merging