[IMP] hr_school: New field "name" in "Tutored by year" object.
avanzosc/hr-addons pull request #52
Opened 2019-05-30 11:44 UTC by alfredoavanzosc

2019-05-30 11:52 UTC, alfredoavanzosc commented
@avanzosc/developers ... review plese

2019-05-30 14:18 UTC, oihane requested changes

2019-05-30 14:18 UTC, oihane commented on hr_school/models/hr_employee.py
> +        string='Description', compute='_compute_name', store=True)
No pongas un campo, lo normal es poner el name_get

2019-05-30 14:42 UTC, alfredoavanzosc commented on hr_school/models/hr_employee.py
> +        string='Description', compute='_compute_name', store=True)
@oihane .. ya he realizado la mejora de programación que me has solicitado. Eskerrik asko.

2019-05-31 06:24 UTC, Daniel-CA approved these changes

2019-06-03 07:35 UTC, oihane commented on hr_school/models/hr_employee.py
> +                u"Academid year: {}, teacher: {}, student: {}").format(
misstype

2019-06-03 08:52 UTC, alfredoavanzosc commented on hr_school/models/hr_employee.py
> +                u"Academid year: {}, teacher: {}, student: {}").format(
misstype?. Que me quieres decir con esto?.

2019-06-03 13:16 UTC, alfredoavanzosc commented on hr_school/models/hr_employee.py
> +                u"Academid year: {}, teacher: {}, student: {}").format(
Realizada la mejora solicitada por @oihane . Eskerrik asko.

2019-06-03 13:21 UTC, mikelarre approved these changes

2019-06-04 09:40 UTC, oihane approved these changes

2019-06-04 09:40 UTC, merged